# Site settings
title: Clara Rules

description: > # this means to ignore newlines until "baseurl:"
  Forward-chaining rules in Clojure.
baseurl: "" # the subpath of your site, e.g. /blog/
## url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

collections:
  docs:
    output: true

# Build settings
markdown: kramdown

# Clara version and documentation location.
clara_version: 0.21.0
javadoc: /apidocs/0.21.0/java/
clojuredoc: /apidocs/0.21.0/clojure/
